---@diagnostic disable: return-type-mismatch
--- Creates a TimingPoint. To place it, you must use an `action`.
---@param time number # The time of the line.
---@param bpm? number # The bpm of the line.
---@param hidden? boolean # Determines if the line (and future lines generated by it) are visible in gameplay.
---@param signature? number # Number of 1/1 snaps that must go by before a timing line is rendered. Analogous to `Signature`/4 in music.
---@return TimingPointInfo
function line(time, bpm, hidden, signature)
    if (hidden == nil) then hidden = false end
    local data = map.GetTimingPointAt(time)

    if (not data) then
        data = {
            Bpm = map.GetCommonBpm(),
            Signature = time_signature.Quadruple,
            Hidden = false
        }
    end

    return utils.CreateTimingPoint(time, bpm or data.Bpm, signature or data.Signature, hidden)
end
